### ISSUE TITLE
Suggestion: Offer portable version

### ISSUE THREAD

**Issue by sbrl** [ViewModelSoftware/HostsEditor#1]
It would be awesome if you offered a portable version - then I could use it on a machine without having to install it. This is especially useful if you use a lot of different machines.

**Comment by tonemackay** [comment]
Thanks for the suggestion. 

I have removed the click once publishing from the latest commit because it was a bit clunky and I have made the app into a portable .exe.

The latest release can be downloaded from the [releases page](https://github.com/ViewModelSoftware/HostsEditor/releases/tag/v1.1.0).

**Comment by sbrl** [comment]
Awesome, thanks!
